name: Browsertrix action
on:
  workflow_dispatch: # trigger manually
    inputs:
        url:
          description: 'Url to crawl'
          required: true

# globals
env:
# build artifacts
  COLLECTION: ""
  INCLUDE_PATH: ""

jobs:
  crawl_url:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Check disk usage
        run: du -h
      
      - name: Get collection name from URL
        run: |
          url=${{ github.event.inputs.url }}
          url=${url/http:\/\//}    # remove http://
          url=${url/https:\/\//}   # remove https://
          url=${url//\./-}         # replace all . with -
          url=${url//\//_}         # replace all / with _
          if [[ ${url:0:(-1)} -eq "_" ]]
          then 
            url=${url:0:(-1)}      # remove final _
          fi
          echo $url
          echo COLLECTION=$url >> $GITHUB_ENV
      
      - name: Get subdomain include from url
        run: |
          includePath=${{ github.event.inputs.url }}
          includePath=${includePath/http:\/\//}    # remove http://
          includePath=${includePath/https:\/\//}   # remove https://
          includePath=${includePath/www./}         # remove www.
          includePath=${includePath/./\\\.}        # replace . with \.
          includePath=".*\.${includePath}"         # add prefix
          
          echo $includePath
          echo INCLUDE_PATH=$includePath >> $GITHUB_ENV
    
      - name: Setup docker
        run: docker pull webrecorder/browsertrix-crawler
      
      - name: Crawl site
        run: docker run -v $PWD/crawls:/crawls/ webrecorder/browsertrix-crawler crawl --workers 16 --saveState always --url ${{ github.event.inputs.url }} --seeds ${{ github.event.inputs.url }} --include ${{ env.INCLUDE_PATH }} --generateWACZ --text --collection ${{ env.COLLECTION }}
     
      - name: Check disk usage
        if: always()
        run: du -h
     
      - run: ls -R
     
      - name: Upload WACZ artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.COLLECTION}}
          path: ${{ github.workspace }}/crawls/collections/${{env.COLLECTION}}/${{env.COLLECTION}}.wacz

      - name: Create issue for finished collection
        if: success()
        id: create-issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.inputs.url }}
          RUN_ID: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        with:
          filename: .github/browsertrix-issue-template.md
