name: Browsertrix action
on:
  workflow_dispatch: # trigger manually
    inputs:
        url:
          description: 'Url to crawl'
          required: true

# globals
env:
# build artifacts
  COLLECTION: ""

jobs:
  crawl_url:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Get collection name from URL
        run: |
          url=${{ github.event.inputs.url }}
          url=${url/http:\/\//}    # remove http://
          url=${url/https:\/\//}   # remove https://
          url=${url//\./_}         # replace all . with _
          url=${url//\//-}         # replace all / with -
          echo $url
          
          echo COLLECTION=$url >> $GITHUB_ENV
      
      - name: Setup docker
        run: docker pull webrecorder/browsertrix-crawler
      
      - name: Crawl site
        run: docker run -v $PWD/crawls:/crawls/ webrecorder/browsertrix-crawler crawl --url ${{ github.event.inputs.url }} --workers 16 --saveState always --generateWACZ --text --collection ${{env.COLLECTION}}
     
      - run: ls -R
     
      - name: Upload WACZ artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.COLLECTION}}
          path: ${{ github.workspace }}/crawls/collections/${{env.COLLECTION}}/${{env.COLLECTION}}.wacz

      - name: Create issue for finished collection
        if: success()
        id: create-issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.inputs.url }}
          RUN_ID: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        with:
          filename: .github/browsertrix-issue-template.md
