name: Browsertrix action
on:
  workflow_dispatch: # trigger manually
    inputs:
        url:
          description: "Url to crawl"
          required: true
        scopetype:
          description: "Scope type"
          required: false
          default: "domain"
        timeout:
          description: "Timeout in s (default: 90s)"
          required: false
          default: "90"
        include_one:
          description: "Include 1"
          required: false
          default: ""
        include_two:
          description: "Include 2"
          required: false
          default: ""
        exclude_one:
          description: "Exclude 1"
          required: false
          default: ""
        exclude_two:
          description: "Exclude 2"
          required: false
          default: ""


# globals
env:
# build artifacts
  COLLECTION: ""
  TIMEOUT: ""
  INCLUDE_ONE: ""
  INCLUDE_TWO: ""
  EXCLUDE_ONE: ""
  EXCLUDE_TWO: ""

jobs:
  crawl_url:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Setup docker
        run: docker pull webrecorder/browsertrix-crawler:latest
       
      - name: Get collection name from URL
        run: |
          url=${{ github.event.inputs.url }}
          url=${url/http:\/\//}    # remove http://
          url=${url/https:\/\//}   # remove https://
          url=${url//\./-}         # replace all . with -
          url=${url//\//_}         # replace all / with _
          
          lastchar=${url: -1}      # check for last char and remove _ if needed 
          if [[ ${lastchar} == "_" ]]
          then 
            url=${url:0:(-1)}
          fi
          
          echo $url
          echo COLLECTION=$url >> $GITHUB_ENV
 
      - name: Set timeout
        if: ${{ github.event.inputs.timeout}}
        run: |
          in=${{ github.event.inputs.timeout }}
          echo TIMEOUT=$in >> $GITHUB_ENV 
 
      - name: Set include option 1
        if: ${{ github.event.inputs.include_one}}
        run: |
          in="--include ${{ github.event.inputs.include_one }}"
          echo INCLUDE_ONE=$in >> $GITHUB_ENV 
      
      - name: Set include option 2
        if: ${{ github.event.inputs.include_two}}
        run: |
          in="--include ${{ github.event.inputs.include_two }}"
          echo INCLUDE_TWO=$in >> $GITHUB_ENV 
      
      - name: Set exclude option 1
        if: ${{ github.event.inputs.exclude_one}}
        run: |
          ex="--exclude ${{ github.event.inputs.exclude_one }}"
          echo EXCLUDE_ONE=$ex >> $GITHUB_ENV 
      
      - name: Set exclude option 2
        if: ${{ github.event.inputs.exclude_two}}
        run: |
          ex="--exclude ${{ github.event.inputs.exclude_two }}"
          echo EXCLUDE_TWO=$ex >> $GITHUB_ENV 
      
      - name: Crawl site
        run: >
          docker run
          -v $PWD/crawls:/crawls/ webrecorder/browsertrix-crawler crawl
          --workers 16
          --saveState always
          --timeout ${{ env.TIMEOUT }}
          --url ${{ github.event.inputs.url }}
          --seeds ${{ github.event.inputs.url }}
          --scopeType ${{ github.event.inputs.scopetype }}
          ${{ env.INCLUDE_ONE }}
          ${{ env.INCLUDE_TWO }}
          ${{ env.EXCLUDE_ONE }}
          ${{ env.EXCLUDE_TWO }}
          --generateWACZ
          --text
          --collection ${{ env.COLLECTION }}
     
      - run: ls -R
     
      - name: Upload WACZ artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.COLLECTION}}
          path: ${{ github.workspace }}/crawls/collections/${{env.COLLECTION}}/${{env.COLLECTION}}.wacz

      - name: Create issue for finished collection
        if: success()
        id: create-issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.inputs.url }}
          RUN_ID: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        with:
          filename: .github/browsertrix-issue-template.md
